[pytest]
DJANGO_SETTINGS_MODULE = ferreteria.settings
python_files = tests.py test_*.py *_tests.py
testpaths =
    core/tests
    warehouse/tests
    sales/tests
addopts = -ra -v --cov --cov-config=.coveragerc --cov-fail-under=100
