# Generated by Django 5.2.14 on 2026-05-20 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="Location")),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="Phone")),
                ("rfc", models.CharField(blank=True, max_length=20, verbose_name="RFC")),
                ("is_default", models.BooleanField(default=False, verbose_name="Default store")),
                (
                    "assigned_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can see and operate this store only.",
                        related_name="assigned_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
                "db_table": "store_ops_store",
                "ordering": ["name"],
            },
        ),
    ]
