# Generated by Django 5.2.14 on 2026-05-20 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU / barcode')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Category')),
                ('department', models.CharField(blank=True, help_text='Store area or department (e.g. plumbing, electrical).', max_length=120, verbose_name='Department')),
                ('location', models.CharField(blank=True, help_text='Shelf, aisle, or bin in the warehouse.', max_length=120, verbose_name='Storage location')),
                ('list_price', models.DecimalField(decimal_places=2, default=0, help_text='Used when scanning at POS; can be overridden on the line.', max_digits=14, verbose_name='Suggested list price')),
                ('reorder_min', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Reorder alert minimum')),
                ('stock_max', models.DecimalField(decimal_places=3, default=0, help_text='Target on-hand quantity. 0 = no cap configured.', max_digits=14, verbose_name='Stock maximum')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'store_ops_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Positive = amount owed before this system.', max_digits=14, verbose_name='Opening balance (payable)')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'store_ops_supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Reference / invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_applied', models.BooleanField(default=False, verbose_name='Stock applied')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier purchase',
                'verbose_name_plural': 'Supplier purchases',
                'db_table': 'store_ops_purchase',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit cost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product', verbose_name='Product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.purchase', verbose_name='Purchase')),
            ],
            options={
                'verbose_name': 'Purchase line',
                'verbose_name_plural': 'Purchase lines',
                'db_table': 'store_ops_purchaseline',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity delta')),
                ('reason', models.CharField(choices=[('purchase', 'Compra proveedor'), ('sale', 'Venta'), ('adjustment', 'Ajuste manual'), ('sale_void', 'Reversión venta'), ('transfer_out', 'Transferencia salida'), ('transfer_in', 'Transferencia entrada')], max_length=20, verbose_name='Reason')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Stock movement',
                'verbose_name_plural': 'Stock movements',
                'db_table': 'store_ops_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Note')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='Store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.supplier', verbose_name='Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Supplier payment',
                'verbose_name_plural': 'Supplier payments',
                'db_table': 'store_ops_supplierpayment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Stock level',
                'verbose_name_plural': 'Stock levels',
                'db_table': 'store_ops_stocklevel',
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='uniq_stock_store_product')],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aceptación'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False, verbose_name='Applied')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected at')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.store', verbose_name='From store')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.store', verbose_name='To store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_accepted', to=settings.AUTH_USER_MODEL, verbose_name='Accepted by')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by')),
            ],
            options={
                'verbose_name': 'Stock transfer',
                'verbose_name_plural': 'Stock transfers',
                'db_table': 'store_ops_stocktransfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product', verbose_name='Product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.stocktransfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Stock transfer line',
                'verbose_name_plural': 'Stock transfer lines',
                'db_table': 'store_ops_stocktransferline',
            },
        ),
    ]
