# Generated by Django 5.2.14 on 2026-05-13 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU / código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Categoría')),
                ('reorder_min', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Stock mínimo alerta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('code', models.SlugField(unique=True, verbose_name='Código')),
                ('is_default', models.BooleanField(default=False, verbose_name='Tienda por defecto')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Positivo = adeudo previo a este sistema.', max_digits=14, verbose_name='Saldo inicial (deuda)')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia / factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_applied', models.BooleanField(default=False, verbose_name='Inventario aplicado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_ops.store', verbose_name='Tienda')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_ops.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra a proveedor',
                'verbose_name_plural': 'Compras a proveedor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Costo unit.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_ops.product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store_ops.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Línea de compra',
                'verbose_name_plural': 'Líneas de compra',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('mixed', 'Mixto')], default='cash', max_length=20, verbose_name='Forma de pago')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notas')),
                ('stock_applied', models.BooleanField(default=False, verbose_name='Inventario aplicado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_ops.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio unit.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_ops.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store_ops.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Línea de venta',
                'verbose_name_plural': 'Líneas de venta',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Delta cantidad')),
                ('reason', models.CharField(choices=[('purchase', 'Compra proveedor'), ('sale', 'Venta'), ('adjustment', 'Ajuste manual'), ('sale_void', 'Reversión venta')], max_length=20, verbose_name='Motivo')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_ops.product', verbose_name='Producto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_ops.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Nota')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_ops.store', verbose_name='Tienda')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_ops.supplier', verbose_name='Proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago a proveedor',
                'verbose_name_plural': 'Pagos a proveedor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_ops.product', verbose_name='Producto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_ops.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='uniq_stock_store_product')],
            },
        ),
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Día operativo')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('export_pdf_path', models.CharField(blank=True, max_length=500)),
                ('export_csv_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_ops.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Cierre de día',
                'verbose_name_plural': 'Cierres de día',
                'constraints': [models.UniqueConstraint(fields=('store', 'date'), name='uniq_dayclose_store_date')],
            },
        ),
    ]
