# Generated by Django 5.2.14 on 2026-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se usa al escanear en caja; puede ajustarse en la línea.', max_digits=14, verbose_name='Precio de venta sugerido'),
        ),
    ]
