# Generated by Django 5.2.14 on 2026-05-20 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada')], default='confirmed', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('mixed', 'Mixto')], default='cash', max_length=20, verbose_name='Payment method')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notes')),
                ('amount_tendered', models.DecimalField(blank=True, decimal_places=2, help_text='Cash received from customer (confirmed cash sales).', max_digits=14, null=True, verbose_name='Amount tendered')),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Change returned (cash sales).', max_digits=14, null=True, verbose_name='Change given')),
                ('stock_applied', models.BooleanField(default=False, verbose_name='Stock applied')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'store_ops_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product', verbose_name='Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Sale line',
                'verbose_name_plural': 'Sale lines',
                'db_table': 'store_ops_saleline',
            },
        ),
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Business date')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('export_pdf_path', models.CharField(blank=True, max_length=500)),
                ('export_csv_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Day close',
                'verbose_name_plural': 'Day closes',
                'db_table': 'store_ops_dayclose',
                'constraints': [models.UniqueConstraint(fields=('store', 'date'), name='uniq_dayclose_store_date')],
            },
        ),
    ]
