# Generated by Django 5.2.15 on 2026-06-26 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Customer')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notes')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'store_ops_quote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product', verbose_name='Product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quote', verbose_name='Quote')),
            ],
            options={
                'verbose_name': 'Quote line',
                'verbose_name_plural': 'Quote lines',
                'db_table': 'store_ops_quoteline',
            },
        ),
    ]
