# Generated by Django 5.2.15 on 2026-06-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_quote_quoteline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='card_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Portion charged to card on mixed payments.', max_digits=14, null=True, verbose_name='Card amount'),
        ),
    ]
